package:
  name: libcouchbase
  version: "2.5.7"

source:
  git_url: https://github.com/couchbase/libcouchbase.git
  git_tag: 2.5.7

requirements:
  build:
    - cmake
    - libevent
    - openssl

  run:
    - libevent
    - openssl
