package:
  name: couchbase
  version: 2.0.7

source:
  git_url: https://github.com/couchbase/couchbase-python-client.git
  git_tag: 2.0.7
  patches:
    - acouchbase.patch

requirements:
  build:
    - libcouchbase
    - python

  run:
    - libcouchbase
    - python
